# Generated by Django 3.1.4 on 2021-07-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Year',
        ),
    ]
