# Generated by Django 3.1.4 on 2021-07-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_graduated',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
