# Generated by Django 3.1.4 on 2021-07-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_date_graduated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='sex',
        ),
    ]
