# Generated by Django 3.1.4 on 2021-07-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Students',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quality_assurance',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to='profile'),
        ),
    ]
