# Generated by Django 3.2.6 on 2021-10-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20211009_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='user.jpg', upload_to='profile'),
        ),
    ]
