# Generated by Django 3.1.4 on 2021-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20210411_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='contact_1',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='contact_2',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='contact_3',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='contact_4',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='contact_5',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='email_id_1',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='email_id_2',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='email_id_3',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='email_id_4',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='email_id_5',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='name_3',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='name_4',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='name_5',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='social_network_id_1',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='social_network_id_2',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='social_network_id_3',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='social_network_id_4',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='social_network_id_5',
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='academic_professional',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='class_size',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='communication_skills',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='critical_thinking_skills',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='extracurricular_activities',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='information_technology_skills',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='interdisciplinary_learning',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='international_community',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='laboratory_resources',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='learning_efficiency',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='library_resources',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='local_community',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='meeting_present',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='opportunities_abroad',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='people_skills',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='personality_development',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='premium_given_research',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='problem_solving_skills',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='professors_knowledge',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='professors_pedagogical',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='quality_instruction',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='range_of_courses',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='relevance_profession',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='research_capability',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='salary_improvement',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='teacher_student_relationships',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='teaching_learning',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='values_formation',
            field=models.CharField(choices=[('Poorly', 'Poorly'), ('Fairly', 'Fairly'), ('Highly', 'Highly'), ('Very Highly', 'Very Highly')], max_length=20),
        ),
    ]
