# Generated by Django 3.1.4 on 2021-05-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20210521_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='depatment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
