# Generated by Django 3.1.4 on 2021-05-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_personalinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='b_address_line_2',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='b_city',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='b_country',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='b_state_province_region',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='b_street_adress',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='b_zip_code',
        ),
    ]
