# Generated by Django 3.1.4 on 2021-05-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_auto_20210523_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='occupational_classification',
        ),
    ]
