# Generated by Django 3.1.4 on 2021-05-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_remove_personalinformation_occupational_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_graduated',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.CharField(max_length=10),
        ),
    ]
