# Generated by Django 3.1.4 on 2021-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_auto_20210524_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='instagram_account',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
