# Generated by Django 3.1.4 on 2021-07-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_personalinformation_instagram_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='finish_graduate_degree',
            field=models.CharField(max_length=200),
        ),
    ]
