# Generated by Django 3.1.4 on 2021-07-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_auto_20210708_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='date_graduated',
        ),
    ]
